equipos = [
{"pais":"Canadá","confederacion":"CONCACAF"},
{"pais":"México","confederacion":"CONCACAF"},
{"pais":"Estados Unidos","confederacion":"CONCACAF"},
{"pais":"Panamá","confederacion":"CONCACAF"},
{"pais":"Haití","confederacion":"CONCACAF"},
{"pais":"Curaçao","confederacion":"CONCACAF"},
{"pais":"Japón","confederacion":"AFC"},
{"pais":"Irán","confederacion":"AFC"},
{"pais":"Corea del Sur","confederacion":"AFC"},
{"pais":"Australia","confederacion":"AFC"},
{"pais":"Arabia Saudita","confederacion":"AFC"},
{"pais":"Qatar","confederacion":"AFC"},
{"pais":"Uzbekistán","confederacion":"AFC"},
{"pais":"Jordania","confederacion":"AFC"},
{"pais":"Argentina","confederacion":"CONMEBOL"},
{"pais":"Ecuador","confederacion":"CONMEBOL"},
{"pais":"Colombia","confederacion":"CONMEBOL"},
{"pais":"Uruguay","confederacion":"CONMEBOL"},
{"pais":"Brasil","confederacion":"CONMEBOL"},
{"pais":"Paraguay","confederacion":"CONMEBOL"},
{"pais":"Nueva Zelanda","confederacion":"OFC"},
{"pais":"Marruecos","confederacion":"CAF"},
{"pais":"Túnez","confederacion":"CAF"},
{"pais":"Egipto","confederacion":"CAF"},
{"pais":"Argelia","confederacion":"CAF"},
{"pais":"Ghana","confederacion":"CAF"},
{"pais":"Cabo Verde","confederacion":"CAF"},
{"pais":"Sudáfrica","confederacion":"CAF"},
{"pais":"Costa de Marfil","confederacion":"CAF"},
{"pais":"Senegal","confederacion":"CAF"},
{"pais":"Inglaterra","confederacion":"UEFA"},
{"pais":"Francia","confederacion":"UEFA"},
{"pais":"Croacia","confederacion":"UEFA"},
{"pais":"Portugal","confederacion":"UEFA"},
{"pais":"Noruega","confederacion":"UEFA"},
{"pais":"Alemania","confederacion":"UEFA"},
{"pais":"Países Bajos","confederacion":"UEFA"},
{"pais":"Bélgica","confederacion":"UEFA"},
{"pais":"Austria","confederacion":"UEFA"},
{"pais":"Suiza","confederacion":"UEFA"},
{"pais":"España","confederacion":"UEFA"},
{"pais":"Escocia","confederacion":"UEFA"}
]